### ISSUE TITLE
Locked folder & files Catalina installer .dmg

### ISSUE THREAD

**Issue by AlfonsoIdem** [miyako/4d-utility-build-application#10]
Could it be possible that Catalina has change any thing that we have to take in account for creating the .dmg ?

When I download the installer .dmg from the web by https I allways get this problem in any computer I have tried.
But if I download the same file installer using FTP no problems.

**Comment by miyako** [comment]
**please be more specific**. I have not idea what you mean by "I always get **this** problem". it does not help either to suddenly mention "**Locked folder**" in your subject with no explanation. 

in general, FTP client or curl ignores all extended attributes, which means GateKeeper has no
thing to check. the quarantine system only applies to browser downloads, Mail app, AirDrop. 

because you share no meaningful information in your post, it is not even a valid question, I am going to have to close it.
